src/StoreOfBuild.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StoreOfBuild.Domain;
using StoreOfBuild.Domain.Account;
using StoreOfBuild.Domain.Products;
using StoreOfBuild.Web.ViewsModels;

namespace StoreOfBuild.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAuthentication _authentication;

        public AccountController(IAuthentication authentication)
        {
            _authentication = authentication;
        }
        
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            var result = await _authentication.Authenticate(model.Email, model.Password);

            if (result)
                return Redirect("/");
            else
            {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View(model);
            }
        }

        public async Task<IActionResult> Logout()
        {
            await _authentication.Logout();
            return Redirect("/Account/Login");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

src/StoreOfBuild.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreOfBuild.Domain;
using StoreOfBuild.Domain.Products;
using StoreOfBuild.Web.ViewsModels;

namespace StoreOfBuild.Web.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class CategoryController : Controller
    {
        private readonly CategoryStorer _categoryStorer;
        private readonly IRepository<Category> _categoryRepository;

        public CategoryController(CategoryStorer categoryStorer,
            IRepository<Category> categoryRepository)
        {
            _categoryStorer = categoryStorer;
            _categoryRepository = categoryRepository;
        }
        
        public IActionResult Index()
        {
            var categories = _categoryRepository.All();
            
            var viewsModels = categories.Select(c => new CategoryViewModel{ Id = c.Id, Name = c.Name });
            return View(viewsModels);
        }

        public IActionResult CreateOrEdit(int id)
        {
            if(id > 0)
            {
                var category = _categoryRepository.GetById(id);
                var categoryViewModel = new CategoryViewModel { Id = category.Id, Name = category.Name };
                return View(categoryViewModel);
            }
            return View();
            
        }

        [HttpPost]
        public IActionResult CreateOrEdit(CategoryViewModel viewModel)
        {
            _categoryStorer.Store(viewModel.Id, viewModel.Name);
            return RedirectToAction("Index");
        }
    }
}

src/StoreOfBuild.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace StoreOfBuild.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/StoreOfBuild.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreOfBuild.Domain;
using StoreOfBuild.Domain.Products;
using StoreOfBuild.Web.ViewsModels;

namespace StoreOfBuild.Web.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class ProductController : Controller
    {
        private readonly ProductStorer _productStorer;
        private readonly IRepository<Product> _productRepository;
        private readonly IRepository<Category> _categoryRepository;

        public ProductController(ProductStorer productStorer,
            IRepository<Category> categoryRepository,
            IRepository<Product> productRepository)
        {
            _productStorer = productStorer;
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }
        
        public IActionResult Index()
        {
            var products = _productRepository.All();
            if(products.Any())
            {
                var viewsModels = products.Select(p => new ProductViewModel { Id = p.Id, Name = p.Name, CategoryName = p.Category.Name});
                return View(viewsModels);
            }
            return View();
        }

        public IActionResult CreateOrEdit(int id)
        {
            var viewModel = new ProductViewModel();
            var categories = _categoryRepository.All();
            viewModel.Categories = categories.Any()
                ? categories.Select(c => new CategoryViewModel {Id = c.Id, Name = c.Name})
                : new List<CategoryViewModel>();
            if (id > 0)
            {
                var product = _productRepository.GetById(id);
                viewModel.Id = product.Id;
                viewModel.Name = product.Name;
                viewModel.CategoryId = product.Category.Id;
                viewModel.Price = product.Price;
                viewModel.StockQuantity = product.StockQuantity;
                return View(viewModel);
            }
            return View(viewModel);
            
        }

        [HttpPost]
        public IActionResult CreateOrEdit(ProductViewModel viewModel)
        {
            _productStorer.Store(viewModel.Id, viewModel.Name, viewModel.CategoryId, viewModel.Price, viewModel.StockQuantity);
            return RedirectToAction("Index");
        }
    }
}

src/StoreOfBuild.Web/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreOfBuild.Domain;
using StoreOfBuild.Domain.Products;
using StoreOfBuild.Domain.Sales;
using StoreOfBuild.Web.ViewsModels;

namespace StoreOfBuild.Web.Controllers
{
    [Authorize]
    public class SaleController : Controller
    {
        private readonly SaleFactory _saleFactory;
        private readonly IRepository<Product> _productRepository;
    

        public SaleController(SaleFactory saleFactory, IRepository<Product> productRepository)
        {
            _saleFactory = saleFactory;
            _productRepository = productRepository;
        }
        
        public IActionResult Create()
        {
            var products = _productRepository.All();
            
            var productsViewModel = products.Select(c => new ProductViewModel{ Id = c.Id, Name = c.Name });
            return View(new SaleViewModel{Products = productsViewModel});
        }

        [HttpPost]
        public IActionResult Create(SaleViewModel viewModel)
        {
            _saleFactory.Create(viewModel.ClientName, viewModel.ProductId, viewModel.Quantity);
            return Ok();
        }
    }
}

src/StoreOfBuild.Web/Controllers/UserController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreOfBuild.Domain.Account;
using StoreOfBuild.Web.ViewsModels;

namespace StoreOfBuild.Web.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class UserController : Controller
    {
        private readonly IManager _manager;

        public UserController(IManager manager){

            _manager = manager;
        }

        public IActionResult Index()
        {
            var users = _manager.ListAll();
            var usersViewModel = users.Select(u => new UserViewModel{Id = u.Id, Email = u.Email});
            return View(usersViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel viewModel)
        {
            await _manager.CreateAsync(viewModel.Email, viewModel.Password, viewModel.Role);
            return Ok();
        }
    }
}

src/StoreOfBuild.Web/Views/Category/CreateOrEdit.cshtml
@model StoreOfBuild.Web.ViewsModels.CategoryViewModel
@{
    ViewData["Title"] = "Category";
}

<div class="row header">
    <div class="col-md-12">
        <h3>Category</h3>
        <a href="/Category" class="btn btn-primary">Back</a>
    </div>
</div>
<div class="row form-wrapper">
    <div class="col-md-12">
        <form id="form" class="form-horizontal" asp-action="CreateOrEdit" asp-controller="Category"
            data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location = '/Category'"              
            asp-anti-forgery>
            <input type="hidden" class="form-control" asp-for="Id" >
            <div class="form-group">
                <label class="col-md-2 control-label">Name</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="Name">    
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <button class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.validate.unobtrusive.js"></script>
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
}

src/StoreOfBuild.Web/Views/Category/Index.cshtml
@model IEnumerable<StoreOfBuild.Web.ViewsModels.CategoryViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row header">
    <div class="col-md-12">
        <h3>Categories</h3>
        <a href="/Category/CreateOrEdit" class="btn btn-primary">New</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <tbody>
                @foreach(var viewModel in @Model)
                {
                    <tr>
                        <td>
                            <a class="name">@viewModel.Name</a>
                        </td>
                        <td>
                            <a href="/Category/CreateOrEdit/@viewModel.Id" class="btn">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/StoreOfBuild.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/StoreOfBuild.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/StoreOfBuild.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <span>Welcome to Store of Build</span>
</div>

src/StoreOfBuild.Web/Views/Product/CreateOrEdit.cshtml
@model StoreOfBuild.Web.ViewsModels.ProductViewModel
@using StoreOfBuild.Web.ViewsModels
@{
    ViewData["Title"] = "Category";
}

<div class="row header">
    <div class="col-md-12">
        <h3>Product</h3>
        <a href="/Product" class="btn btn-primary">Back</a>
    </div>
</div>
<div class="row form-wrapper">
    <div class="col-md-12">
        <form id="form" class="form-horizontal" asp-action="CreateOrEdit" asp-controller="Product" 
            data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location = '/Product'"
            asp-anti-forgery>
            <input type="hidden" class="form-control" asp-for="Id" >
            <div class="form-group">
                <label class="col-md-2 control-label">Name</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="Name" >    
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Category</label>
                <div class="col-md-2">
                    <select class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(@Model.Categories,"Id","Name"))">
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Price</label>
                <div class="col-md-8">
                    <input id="price" type="text" class="form-control" asp-for="Price" >
                    <span asp-validation-for="Price" class="text-danger"></span>        
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Stock Quantity</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="StockQuantity" >
                    <span asp-validation-for="StockQuantity" class="text-danger"></span>    
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <button class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.validate.unobtrusive.js"></script>
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://cdn.jsdelivr.net/autonumeric/2.0.0/autoNumeric.min.js"></script>
    <script>
        $(function(){
            $('#price').autoNumeric('init');
        });
    </script>
}

src/StoreOfBuild.Web/Views/Product/Index.cshtml
@model IEnumerable<StoreOfBuild.Web.ViewsModels.ProductViewModel>
@{
    ViewData["Title"] = "Product";
}

<div class="row header">
    <div class="col-md-12">
        <h3>Products</h3>
        <a href="/Product/CreateOrEdit" class="btn btn-primary">New</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <tbody>
                @if(@Model != null)
                {
                    foreach(var viewModel in @Model)
                    {
                        <tr>
                            <td>
                                <a class="name">@viewModel.Name</a>
                            </td>
                            <td>
                                <a class="name">@viewModel.CategoryName</a>
                            </td>
                            <td>
                                <a href="/Product/CreateOrEdit/@viewModel.Id" class="btn">Edit</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

src/StoreOfBuild.Web/Views/Sale/Create.cshtml
@model StoreOfBuild.Web.ViewsModels.SaleViewModel
@using StoreOfBuild.Web.ViewsModels
@{
    ViewData["Title"] = "Sale";
}

<div class="row header">
    <div class="col-md-12">
        <h3>Sales</h3>
        <a href="/Sale/Create" class="btn btn-primary">New</a>
    </div>
</div>
<div class="row form-wrapper">
    <div class="col-md-12">
        <form id="form" class="form-horizontal" asp-action="Create" asp-controller="Sale" 
            data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location = '/Sale/Create'"
            asp-anti-forgery>
            <div class="form-group">
                <label class="col-md-2 control-label">Client Name</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="ClientName" >    
                    <span asp-validation-for="ClientName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Product</label>
                <div class="col-md-2">
                    <select id="product" class="form-control" asp-for="ProductId" asp-items="@(new SelectList(@Model.Products,"Id","Name"))">
                        <option value="NoValue"></option>
                    </select>
                    <span class="text-danger" asp-validation-for="ProductId"></span>    
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Quantity</label>
                <div class="col-md-8">
                    <input id="quantity" type="text" class="form-control" asp-for="Quantity" >
                    <span class="text-danger" asp-validation-for="Quantity"></span>    
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <button class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.validate.unobtrusive.js"></script>
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
}

src/StoreOfBuild.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Store Of Build</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="User" asp-action="Index">User</a></li>
                    <li><a asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                    <li><a asp-area="" asp-controller="Sale" asp-action="Create">Sale</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/Account/Logout" type="submit" class="btn btn-link navbar-btn navbar-link">Log out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Store Of Build</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @RenderSection("Scripts", required: false)
    
</body>
</html>

src/StoreOfBuild.Web/Views/User/Create.cshtml
@model StoreOfBuild.Web.ViewsModels.UserViewModel
@{
    ViewData["Title"] = "User";
}

<div class="row header">
    <div class="col-md-12">
        <h3>User</h3>
        <a href="/User" class="btn btn-primary">Back</a>
    </div>
</div>
<div class="row form-wrapper">
    <div class="col-md-12">
        <form id="form" class="form-horizontal" asp-action="Create" asp-controller="User"
            data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location = '/User'"
            asp-anti-forgery>
            <input type="hidden" class="form-control" asp-for="Id" >
            <div class="form-group">
                <label class="col-md-2 control-label">Email</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="Email">    
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Password</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="Password">    
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Role</label>
                <div class="col-md-2">
                    <select class="form-control" asp-for="Role">
                        <option></option>
                        <option value="Manager">Manager</option>
                        <option value="Operation">Operation</option>
                    </select>
                    
                    <span asp-validation-for="Role" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-8">
                    <button class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.validate.unobtrusive.js"></script>
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
}

src/StoreOfBuild.Web/Views/User/Index.cshtml
@model IEnumerable<StoreOfBuild.Web.ViewsModels.UserViewModel>
@{
    ViewData["Title"] = "User";
}

<div class="row header">
    <div class="col-md-12">
        <h3>Users</h3>
        <a href="/User/Create" class="btn btn-primary">New</a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <tbody>
                @if(@Model != null)
                {
                    foreach(var viewModel in @Model)
                    {
                        <tr>
                            <td>
                                <a class="name">@viewModel.Email</a>
                            </td>
                            <td>
                                <a href="/User/ChangePassword/@viewModel.Id" class="btn">Change password</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>